apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-mreo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-mreo
    app.kubernetes.io/part-of: load-app-33bab9c5-b619-426b-9e83-a5e55a33bb5d
  name: devfile-sample-python-basic-mreo
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-mreo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-mreo
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/test-rhtap-3-tenant/load-app-33bab9c5-b619-426b-9e83-a5e55a33bb5d/devfile-sample-python-basic-mreo@sha256:69250e6ca8bdba74616ea4ae005cede3aa2a7c2bd36b18b4057b6bcff61b2469
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
